version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8082:80" # Port pour l'API Symfony
    volumes:
      - ./docker/nginx:/nginx:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/var/www/app:rw
    depends_on:
      - postgres
    ports:
      - "8081:80"
    environment:
      APP_ENV: dev

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app:rw
    depends_on:
      - backend
    environment:
      ANGULAR_VERSION: latest

volumes:
  postgres_data:
